services: 
  postgres:
    container_name: api-node-shopper
    image: postgres
    ports: 
      - 5432:5432
    environment: 
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: shopper
      PGDATA: /data/bitnami/postgresql
    volumes: 
      - ./data/pg:/data/bitnami/postgresql
