services: 
  api-node-shopper:
    image: bitnami/postgresql
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=shopper
      - PGDATA=/data/postgres
    volumes: 
      - ./data/pg:/data/postgres
