### Variable
@baseUrl = http://localhost:3333

### Receive an image and consult in Gemini and return the measurement read by the API
POST {{baseUrl}}/upload
Content-Type: application/json

{
  "image": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAAAAAAAD/4QBaRXhpZgAATU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAA...",
  "customer_code": "123456",
  "measure_datetime": "2024-08-29T10:00:00Z",
  "measure_type": "WATER"
}

### Confirm or correct the value read by LLM
PATCH {{baseUrl}}/confirm
Content-Type: application/json

{
  "measure_uuid": "{uuid}",
  "confirmed_value": 123
}

### Lists the measurements performed by a specific client
GET {{baseUrl}}/{customer_code}/list
Accept: application/json

### Testa erro 400 ao passar um measure_type inválido
GET {{baseUrl}}/{customer_code}/list?measure_type=INVALID_TYPE
Accept: application/json