### Variable
@baseUrl = http://localhost:3333

### Receive an image and consult in Gemini and return the measurement read by the API
POST {{baseUrl}}/upload
Content-Type: application/json

{
  "imageUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAAD8GO2jAAAAC0lEQVR42mP8/wcAAwAB/1VZ6UAAAAABJRU5ErkJggg==",
  "customerCode": "12345",
  "measureDatetime": "2024-08-29T10:00:00Z",
  "measureType": "WATER"
}

### Confirm or correct the value read by LLM
PATCH {{baseUrl}}/confirm
Content-Type: application/json

{
  "measure_uuid": "1583d9ab-51d9-4807-a2bf-9a7f697b9b36",
  "confirmed_value": 123
}

### Lists the measurements performed by a specific client
### List measurements for a specific client
GET {{baseUrl}}/{customer_code}/list?measure_type=GAS
Accept: application/json

### List measures for a specific customer without type filter
GET {{baseUrl}}/{customer_code}/list
Accept: application/json
